language: ruby
dist: xenial
cache: bundler

matrix:
  include:
    - rvm: 2.1
      gemfile: gems/rails3.gemfile
    - rvm: 2.2
    - rvm: 2.3
    - rvm: 2.4
    - rvm: 2.5
    - rvm: 2.6
    - rvm: 3.0
    - rvm: 2.6
      gemfile: gems/octoshark.gemfile
    - rvm: 2.6
      name: rubocop yo
      script: bundle exec rubocop
    - rvm: 2.6
      gemfile: gems/rails3.gemfile
